language: node_js
os:
  - linux
sudo: true
env:
  - CXX=g++-4.8 TRAVIS=true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
after_success: npm run coveralls
before_install:
  # TODO: these two commands are required to enable IPv6,
  # they shouldn't exist, please revert once more official solutions appeared.
  # see https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
  - echo '{"ipv6":true,"fixed-cidr-v6":"fe80::/64"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
